build:
  image: docker:stable
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t registry.alt-tools.tech/gptriome/back:$CI_COMMIT_BRANCH .
    - docker push  registry.alt-tools.tech/gptriome/back:$CI_COMMIT_BRANCH
  rules:
    - when: manual
